# Generated by Django 3.1.2 on 2020-11-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.CharField(blank=True, default='unset', max_length=100),
        ),
    ]
