# Generated by Django 3.1.2 on 2020-10-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='day_added',
            field=models.DateField(auto_now=True),
        ),
    ]
