# Generated by Django 3.1.2 on 2020-10-24 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_day_added'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('product_id', 'day_added')},
        ),
    ]
