# Generated by Django 3.1.2 on 2021-01-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20201119_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='day_added',
        ),
        migrations.AddField(
            model_name='deal',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.CharField(blank=True, default='unset', max_length=250),
        ),
    ]
